
    create table attendance_record (
        id_lesson_session integer not null,
        id_user_student integer not null,
        id_attendance char(10) not null,
        status varchar(10) not null check ((status in ('PRESENTE','AUSENTE','ABONADO'))),
        primary key (id_attendance)
    );

    create table class (
        date date not null,
        id_class integer generated by default as identity,
        primary key (id_class)
    );

    create table examining_board (
        date date not null,
        grade numeric(10,5) not null,
        id integer generated by default as identity,
        id_user_student integer not null,
        room varchar(255) not null,
        primary key (id)
    );

    create table hours_report (
        id_report integer not null,
        total_time_seconds integer,
        entry_time timestamp with time zone not null,
        exit_time timestamp with time zone,
        activities varchar(1250),
        rejection_justification varchar(255),
        status varchar(255) not null check ((status in ('PENDING','APPROVED','REJECTED'))),
        primary key (id_report)
    );

    create table lesson_session (
        date date not null,
        id_class integer not null,
        id_lesson_session integer generated by default as identity,
        id_user_teacher integer not null,
        primary key (id_lesson_session)
    );

    create table password_reset_tokens (
        id_user integer not null,
        used boolean not null,
        created_at timestamp(6) not null,
        expires_at timestamp(6) not null,
        id uuid not null,
        token varchar(255) not null unique,
        primary key (id)
    );

    create table project (
        id_project integer generated by default as identity,
        id_user_teacher integer not null,
        period char(10) not null,
        status char(10) not null,
        description varchar(255) not null,
        git_lab_link varchar(255),
        name varchar(255) not null,
        observation varchar(255),
        primary key (id_project)
    );

    create table report (
        create_date date not null,
        edit_date date not null,
        grade numeric(4,2),
        id_project integer not null,
        id_report integer generated by default as identity,
        id_user_student integer not null,
        type varchar(10) not null check ((type in ('RA','RF','SPRINT','HOURS'))),
        primary key (id_report)
    );

    create table report_archive (
        id_report integer not null,
        url_archive varchar(255) not null,
        primary key (id_report)
    );

    create table report_review (
        id_report integer not null,
        revision_date timestamp with time zone not null,
        comment varchar(255) not null,
        correction_url varchar(255) not null,
        primary key (id_report)
    );

    create table schedule (
        event_date date not null,
        event_time time(0) not null,
        id_schedule integer generated by default as identity,
        id_user_admin integer not null,
        event char(10) not null,
        event_period char(10) not null,
        primary key (id_schedule)
    );

    create table sprint_report (
        id_report integer not null,
        sprint char(2) not null,
        activity_completed varchar(255) not null,
        learned_lessons varchar(255) not null,
        next_steps varchar(255) not null,
        predicted_activity varchar(255) not null,
        problems_encountered varchar(255) not null,
        primary key (id_report)
    );

    create table student_historic (
        grade numeric(5,2) not null,
        id_class integer not null,
        id_project integer not null,
        id_student_historic integer generated by default as identity,
        id_user_student integer not null,
        semester_year smallint not null,
        primary key (id_student_historic)
    );

    create table student_profile (
        ages_position integer not null,
        id_profile integer generated by default as identity,
        id_team integer not null,
        id_user_student integer not null,
        course varchar(255) not null,
        image_url varchar(255),
        primary key (id_profile)
    );

    create table teacher_examining_board (
        id integer generated by default as identity,
        id_examining_board integer not null,
        id_user_teacher integer not null,
        primary key (id)
    );

    create table team (
        id_project integer not null,
        id_team integer generated by default as identity,
        id_user_teacher integer not null,
        primary key (id_team)
    );

    create table "user" (
        id_user integer generated by default as identity,
        enrollment_number varchar(20) not null unique,
        type varchar(20) not null,
        email varchar(255) not null unique,
        name varchar(255) not null,
        password varchar(255) not null,
        primary key (id_user)
    );

    alter table if exists attendance_record 
       add constraint FK6a39vf9ahadq2702l6affk7tb 
       foreign key (id_lesson_session) 
       references lesson_session;

    alter table if exists attendance_record 
       add constraint FK4kksupb3297qaiygn6lwv0r03 
       foreign key (id_user_student) 
       references "user";

    alter table if exists examining_board 
       add constraint FK3s0c66jemjn1kbb0yk1k39n12 
       foreign key (id_user_student) 
       references "user";

    alter table if exists hours_report 
       add constraint FKlas4lw3pcdey6gjinm8e75ykd 
       foreign key (id_report) 
       references report;

    alter table if exists lesson_session 
       add constraint FKc35rc9i4cfonwl2ujc55pbgcj 
       foreign key (id_class) 
       references class;

    alter table if exists lesson_session 
       add constraint FKl6l5gt1vech7w8o8060u4k19d 
       foreign key (id_user_teacher) 
       references "user";

    alter table if exists password_reset_tokens 
       add constraint FKd85xs28k2gbxcjrl6t38f84a3 
       foreign key (id_user) 
       references "user";

    alter table if exists project 
       add constraint FKlnal40p6ppmdvh1slc5i9a52d 
       foreign key (id_user_teacher) 
       references "user";

    alter table if exists report 
       add constraint FKpruq9ow6uaeh9ly8l573ve248 
       foreign key (id_project) 
       references project;

    alter table if exists report 
       add constraint FKrppisgkj8yte7eropfc508eb4 
       foreign key (id_user_student) 
       references "user";

    alter table if exists report_archive 
       add constraint FKnn0f9lv0p0ayh39ur0hdj8pcm 
       foreign key (id_report) 
       references report;

    alter table if exists report_review 
       add constraint FK640wcd0xu2w0jom9hpbl046da 
       foreign key (id_report) 
       references report;

    alter table if exists schedule 
       add constraint FKdm8cjapjcs2a33mgjafcbrq3v 
       foreign key (id_user_admin) 
       references "user";

    alter table if exists sprint_report 
       add constraint FKqho8jk6hyjtffbbd83kn5uthj 
       foreign key (id_report) 
       references report;

    alter table if exists student_historic 
       add constraint FKqvhb2e0wg15i10vwrv9g3plbd 
       foreign key (id_class) 
       references class;

    alter table if exists student_historic 
       add constraint FK375cdu9b0wewuh4joqxq9o0b 
       foreign key (id_project) 
       references project;

    alter table if exists student_historic 
       add constraint FKsoqkqpacxi7h4egbf4yxfainr 
       foreign key (id_user_student) 
       references "user";

    alter table if exists student_profile 
       add constraint FKj8bidna10r1dvxgltb0kgl4op 
       foreign key (id_user_student) 
       references "user";

    alter table if exists student_profile 
       add constraint FK249tol2sm4egwcvytgxejfc1q 
       foreign key (id_team) 
       references team;

    alter table if exists teacher_examining_board 
       add constraint FKgahflxt9fuktv0d82faqrso7h 
       foreign key (id_examining_board) 
       references examining_board;

    alter table if exists teacher_examining_board 
       add constraint FK76uns7bs6f17unp5vtb32javg 
       foreign key (id_user_teacher) 
       references "user";

    alter table if exists team 
       add constraint FKok1m60njs4scy9iekna6cuwet 
       foreign key (id_project) 
       references project;

    alter table if exists team 
       add constraint FKmejlopmd4xaye6vs2rljidyh4 
       foreign key (id_user_teacher) 
       references "user";
