# Conex�o JDBC - O formato � ${VARIAVEL:VALOR_PADRAO}
spring.datasource.url=jdbc:postgresql://localhost:${DB_PORT:5432}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=8081

spring.config.import=optional:file:.env[.properties]

# Garante que o JPA crie as tabelas PRIMEIRO
spring.jpa.defer-datasource-initialization=true

# Garante que o Spring rode o data.sql LOGO EM SEGUIDA
spring.sql.init.mode=always

# Configurações do Mailtrap
spring.mail.host=${MAIL_HOST:sandbox.smtp.mailtrap.io}
spring.mail.port=${MAIL_PORT:2525}
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
app.upload.dir=uploads
