# Perfil "dev" (Ativado por padrão para Docker / Desenvolvimento Local)
spring.flyway.enabled=false

# Banco local configurado pelo docker-compose
spring.datasource.url=jdbc:postgresql://localhost:${DB_PORT:5432}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}

# Delega a criacao das tabelas para as @Entity
spring.jpa.hibernate.ddl-auto=update

# Ativa o mapeamento inicial (data.sql)
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
