# Conex�o JDBC - O formato � ${VARIAVEL:VALOR_PADRAO}
spring.datasource.url=jdbc:postgresql://localhost:${DB_PORT:5432}/${DB_NAME}
spring.datasource.username=${DB_USER}
spring.datasource.password=${DB_PASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

# Configura��es do Hibernate (Code-First)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
server.port=8081

spring.config.import=optional:file:.env[.properties]