# Perfil "prod" (Subir para o Amazon RDS)
spring.flyway.enabled=true

# Banco RDS preenchido via variaveis de ambiente
spring.datasource.url=${DB_URLRDS}
spring.datasource.username=${DB_USERNAMERDS}
spring.datasource.password=${DB_PASSWORDRDS}

# NUNCA crie/atualize tabelas sozinho em producao, confie no Flyway
spring.jpa.hibernate.ddl-auto=validate

# Ignora o script data.sql base na inicializacao
spring.jpa.defer-datasource-initialization=false
spring.sql.init.mode=never
