--
-- PostgreSQL database dump
--



-- Dumped from database version 15.17
-- Dumped by pg_dump version 15.17

SET statement_timeout = 0;
SET lock_timeout = 0;
SET idle_in_transaction_session_timeout = 0;
SET client_encoding = 'UTF8';
SET standard_conforming_strings = on;
SELECT pg_catalog.set_config('search_path', '', false);
SET check_function_bodies = false;
SET xmloption = content;
SET client_min_messages = warning;
SET row_security = off;

SET default_tablespace = '';

SET default_table_access_method = heap;

--
-- Name: attendance_record; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.attendance_record (
    id_attendance character(10) NOT NULL,
    status character varying(10) NOT NULL,
    id_lesson_session integer NOT NULL,
    id_user_student integer NOT NULL,
    CONSTRAINT attendance_record_status_check CHECK (((status)::text = ANY ((ARRAY['PRESENTE'::character varying, 'AUSENTE'::character varying, 'ABONADO'::character varying])::text[])))
);


--
-- Name: class; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.class (
    id_class integer NOT NULL,
    date date NOT NULL,
    date_time character varying(255)
);


--
-- Name: class_id_class_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.class ALTER COLUMN id_class ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.class_id_class_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: examining_board; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.examining_board (
    id integer NOT NULL,
    date date NOT NULL,
    grade numeric(10,5) NOT NULL,
    room character varying(255) NOT NULL,
    id_user_student integer NOT NULL
);


--
-- Name: examining_board_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.examining_board ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.examining_board_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: grade; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.grade (
    id_grade integer NOT NULL,
    type integer NOT NULL,
    value integer NOT NULL,
    id_student_historic integer NOT NULL
);


--
-- Name: grade_id_grade_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.grade ALTER COLUMN id_grade ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.grade_id_grade_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: hours_report; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.hours_report (
    activities character varying(1250),
    entry_time timestamp with time zone NOT NULL,
    exit_time timestamp with time zone,
    rejection_justification character varying(255),
    status character varying(255) NOT NULL,
    total_time_seconds integer,
    id_report integer NOT NULL,
    CONSTRAINT hours_report_status_check CHECK (((status)::text = ANY ((ARRAY['PENDING'::character varying, 'APPROVED'::character varying, 'REJECTED'::character varying])::text[])))
);


--
-- Name: lesson_session; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.lesson_session (
    id_lesson_session integer NOT NULL,
    date date NOT NULL,
    id_class integer NOT NULL,
    id_user_teacher integer NOT NULL
);


--
-- Name: lesson_session_id_lesson_session_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.lesson_session ALTER COLUMN id_lesson_session ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.lesson_session_id_lesson_session_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: password_reset_tokens; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.password_reset_tokens (
    id uuid NOT NULL,
    created_at timestamp(6) without time zone NOT NULL,
    expires_at timestamp(6) without time zone NOT NULL,
    token character varying(255) NOT NULL,
    used boolean NOT NULL,
    id_user integer NOT NULL
);


--
-- Name: project; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.project (
    id_project integer NOT NULL,
    description character varying(255) NOT NULL,
    git_lab_link character varying(255),
    name character varying(255) NOT NULL,
    observation character varying(255),
    period character(10) NOT NULL,
    status character(10) NOT NULL,
    id_user_teacher integer NOT NULL
);


--
-- Name: project_id_project_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.project ALTER COLUMN id_project ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.project_id_project_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: report; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.report (
    id_report integer NOT NULL,
    create_date timestamp with time zone NOT NULL,
    edit_date timestamp with time zone NOT NULL,
    grade numeric(4,2),
    type character varying(10) NOT NULL,
    id_project integer NOT NULL,
    id_user_student integer NOT NULL,
    CONSTRAINT report_type_check CHECK (((type)::text = ANY ((ARRAY['RA'::character varying, 'RF'::character varying, 'SPRINT'::character varying, 'HOURS'::character varying])::text[])))
);


--
-- Name: report_archive; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.report_archive (
    url_archive character varying(255) NOT NULL,
    id_report integer NOT NULL
);


--
-- Name: report_id_report_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.report ALTER COLUMN id_report ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.report_id_report_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: report_review; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.report_review (
    comment character varying(255) NOT NULL,
    correction_url character varying(255) NOT NULL,
    revision_date timestamp with time zone NOT NULL,
    id_report integer NOT NULL
);


--
-- Name: schedule; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.schedule (
    id_schedule integer NOT NULL,
    event character(10) NOT NULL,
    event_date date NOT NULL,
    event_period character(10) NOT NULL,
    event_time time(0) without time zone NOT NULL
);


--
-- Name: schedule_id_schedule_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.schedule ALTER COLUMN id_schedule ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.schedule_id_schedule_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: sprint_report; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.sprint_report (
    activity_completed character varying(255) NOT NULL,
    learned_lessons character varying(255) NOT NULL,
    next_steps character varying(255) NOT NULL,
    predicted_activity character varying(255) NOT NULL,
    problems_encountered character varying(255) NOT NULL,
    sprint character(2) NOT NULL,
    id_report integer NOT NULL
);


--
-- Name: student_historic; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.student_historic (
    id_student_historic integer NOT NULL,
    ages_level integer NOT NULL,
    grade numeric(5,2) NOT NULL,
    semester_year character varying(255) NOT NULL,
    student_status character varying(255) NOT NULL,
    id_class integer NOT NULL,
    id_project integer NOT NULL,
    id_user_student integer NOT NULL
);


--
-- Name: student_historic_id_student_historic_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.student_historic ALTER COLUMN id_student_historic ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_historic_id_student_historic_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: student_profile; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.student_profile (
    id_profile integer NOT NULL,
    ages_position integer NOT NULL,
    course character varying(255) NOT NULL,
    image_url character varying(255),
    id_user_student integer NOT NULL,
    id_team integer NOT NULL
);


--
-- Name: student_profile_id_profile_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.student_profile ALTER COLUMN id_profile ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.student_profile_id_profile_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: student_technology; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.student_technology (
    id_user_student integer NOT NULL,
    id_technology integer NOT NULL
);


--
-- Name: teacher_examining_board; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.teacher_examining_board (
    id integer NOT NULL,
    id_examining_board integer NOT NULL,
    id_user_teacher integer NOT NULL
);


--
-- Name: teacher_examining_board_id_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.teacher_examining_board ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.teacher_examining_board_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: team; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.team (
    id_team integer NOT NULL,
    id_project integer NOT NULL,
    id_user_teacher integer NOT NULL
);


--
-- Name: team_id_team_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.team ALTER COLUMN id_team ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.team_id_team_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: technology; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public.technology (
    id_technology integer NOT NULL,
    name character varying(255) NOT NULL
);


--
-- Name: technology_id_technology_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public.technology ALTER COLUMN id_technology ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.technology_id_technology_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: user; Type: TABLE; Schema: public; Owner: -
--

CREATE TABLE public."user" (
    id_user integer NOT NULL,
    email character varying(255) NOT NULL,
    enrollment_number character varying(20) NOT NULL,
    name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    type character varying(20) NOT NULL
);


--
-- Name: user_id_user_seq; Type: SEQUENCE; Schema: public; Owner: -
--

ALTER TABLE public."user" ALTER COLUMN id_user ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_id_user_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);


--
-- Name: attendance_record attendance_record_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendance_record
    ADD CONSTRAINT attendance_record_pkey PRIMARY KEY (id_attendance);


--
-- Name: class class_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.class
    ADD CONSTRAINT class_pkey PRIMARY KEY (id_class);


--
-- Name: examining_board examining_board_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.examining_board
    ADD CONSTRAINT examining_board_pkey PRIMARY KEY (id);


--
-- Name: grade grade_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.grade
    ADD CONSTRAINT grade_pkey PRIMARY KEY (id_grade);


--
-- Name: hours_report hours_report_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.hours_report
    ADD CONSTRAINT hours_report_pkey PRIMARY KEY (id_report);


--
-- Name: lesson_session lesson_session_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lesson_session
    ADD CONSTRAINT lesson_session_pkey PRIMARY KEY (id_lesson_session);


--
-- Name: password_reset_tokens password_reset_tokens_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id);


--
-- Name: project project_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project
    ADD CONSTRAINT project_pkey PRIMARY KEY (id_project);


--
-- Name: report_archive report_archive_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.report_archive
    ADD CONSTRAINT report_archive_pkey PRIMARY KEY (id_report);


--
-- Name: report report_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.report
    ADD CONSTRAINT report_pkey PRIMARY KEY (id_report);


--
-- Name: report_review report_review_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.report_review
    ADD CONSTRAINT report_review_pkey PRIMARY KEY (id_report);


--
-- Name: schedule schedule_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.schedule
    ADD CONSTRAINT schedule_pkey PRIMARY KEY (id_schedule);


--
-- Name: sprint_report sprint_report_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sprint_report
    ADD CONSTRAINT sprint_report_pkey PRIMARY KEY (id_report);


--
-- Name: student_historic student_historic_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_historic
    ADD CONSTRAINT student_historic_pkey PRIMARY KEY (id_student_historic);


--
-- Name: student_profile student_profile_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_profile
    ADD CONSTRAINT student_profile_pkey PRIMARY KEY (id_profile);


--
-- Name: student_technology student_technology_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_technology
    ADD CONSTRAINT student_technology_pkey PRIMARY KEY (id_user_student, id_technology);


--
-- Name: teacher_examining_board teacher_examining_board_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teacher_examining_board
    ADD CONSTRAINT teacher_examining_board_pkey PRIMARY KEY (id);


--
-- Name: team team_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.team
    ADD CONSTRAINT team_pkey PRIMARY KEY (id_team);


--
-- Name: technology technology_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.technology
    ADD CONSTRAINT technology_pkey PRIMARY KEY (id_technology);


--
-- Name: password_reset_tokens uk71lqwbwtklmljk3qlsugr1mig; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT uk71lqwbwtklmljk3qlsugr1mig UNIQUE (token);


--
-- Name: technology uk7lsjqbr6g2jexyhbknslswkjc; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.technology
    ADD CONSTRAINT uk7lsjqbr6g2jexyhbknslswkjc UNIQUE (name);


--
-- Name: user ukhl4ga9r00rh51mdaf20hmnslt; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT ukhl4ga9r00rh51mdaf20hmnslt UNIQUE (email);


--
-- Name: user ukqon9ht1p7j7nj8l5378cu804b; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT ukqon9ht1p7j7nj8l5378cu804b UNIQUE (enrollment_number);


--
-- Name: user user_pkey; Type: CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public."user"
    ADD CONSTRAINT user_pkey PRIMARY KEY (id_user);


--
-- Name: student_profile fk249tol2sm4egwcvytgxejfc1q; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_profile
    ADD CONSTRAINT fk249tol2sm4egwcvytgxejfc1q FOREIGN KEY (id_team) REFERENCES public.team(id_team);


--
-- Name: student_historic fk375cdu9b0wewuh4joqxq9o0b; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_historic
    ADD CONSTRAINT fk375cdu9b0wewuh4joqxq9o0b FOREIGN KEY (id_project) REFERENCES public.project(id_project);


--
-- Name: examining_board fk3s0c66jemjn1kbb0yk1k39n12; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.examining_board
    ADD CONSTRAINT fk3s0c66jemjn1kbb0yk1k39n12 FOREIGN KEY (id_user_student) REFERENCES public."user"(id_user);


--
-- Name: attendance_record fk4kksupb3297qaiygn6lwv0r03; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendance_record
    ADD CONSTRAINT fk4kksupb3297qaiygn6lwv0r03 FOREIGN KEY (id_user_student) REFERENCES public."user"(id_user);


--
-- Name: student_technology fk5wcmsnb94724nbtgd8dggd2b2; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_technology
    ADD CONSTRAINT fk5wcmsnb94724nbtgd8dggd2b2 FOREIGN KEY (id_user_student) REFERENCES public."user"(id_user);


--
-- Name: report_review fk640wcd0xu2w0jom9hpbl046da; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.report_review
    ADD CONSTRAINT fk640wcd0xu2w0jom9hpbl046da FOREIGN KEY (id_report) REFERENCES public.report(id_report);


--
-- Name: attendance_record fk6a39vf9ahadq2702l6affk7tb; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.attendance_record
    ADD CONSTRAINT fk6a39vf9ahadq2702l6affk7tb FOREIGN KEY (id_lesson_session) REFERENCES public.lesson_session(id_lesson_session);


--
-- Name: teacher_examining_board fk76uns7bs6f17unp5vtb32javg; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teacher_examining_board
    ADD CONSTRAINT fk76uns7bs6f17unp5vtb32javg FOREIGN KEY (id_user_teacher) REFERENCES public."user"(id_user);


--
-- Name: grade fkac2qthcpmigjih8vqxipyp8cd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.grade
    ADD CONSTRAINT fkac2qthcpmigjih8vqxipyp8cd FOREIGN KEY (id_student_historic) REFERENCES public.student_historic(id_student_historic);


--
-- Name: student_technology fkc0uswv1l41u129gp9dsc4eys0; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_technology
    ADD CONSTRAINT fkc0uswv1l41u129gp9dsc4eys0 FOREIGN KEY (id_technology) REFERENCES public.technology(id_technology);


--
-- Name: lesson_session fkc35rc9i4cfonwl2ujc55pbgcj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lesson_session
    ADD CONSTRAINT fkc35rc9i4cfonwl2ujc55pbgcj FOREIGN KEY (id_class) REFERENCES public.class(id_class);


--
-- Name: password_reset_tokens fkd85xs28k2gbxcjrl6t38f84a3; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.password_reset_tokens
    ADD CONSTRAINT fkd85xs28k2gbxcjrl6t38f84a3 FOREIGN KEY (id_user) REFERENCES public."user"(id_user);


--
-- Name: teacher_examining_board fkgahflxt9fuktv0d82faqrso7h; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.teacher_examining_board
    ADD CONSTRAINT fkgahflxt9fuktv0d82faqrso7h FOREIGN KEY (id_examining_board) REFERENCES public.examining_board(id);


--
-- Name: student_profile fkj8bidna10r1dvxgltb0kgl4op; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_profile
    ADD CONSTRAINT fkj8bidna10r1dvxgltb0kgl4op FOREIGN KEY (id_user_student) REFERENCES public."user"(id_user);


--
-- Name: lesson_session fkl6l5gt1vech7w8o8060u4k19d; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.lesson_session
    ADD CONSTRAINT fkl6l5gt1vech7w8o8060u4k19d FOREIGN KEY (id_user_teacher) REFERENCES public."user"(id_user);


--
-- Name: hours_report fklas4lw3pcdey6gjinm8e75ykd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.hours_report
    ADD CONSTRAINT fklas4lw3pcdey6gjinm8e75ykd FOREIGN KEY (id_report) REFERENCES public.report(id_report);


--
-- Name: project fklnal40p6ppmdvh1slc5i9a52d; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.project
    ADD CONSTRAINT fklnal40p6ppmdvh1slc5i9a52d FOREIGN KEY (id_user_teacher) REFERENCES public."user"(id_user);


--
-- Name: team fkmejlopmd4xaye6vs2rljidyh4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.team
    ADD CONSTRAINT fkmejlopmd4xaye6vs2rljidyh4 FOREIGN KEY (id_user_teacher) REFERENCES public."user"(id_user);


--
-- Name: report_archive fknn0f9lv0p0ayh39ur0hdj8pcm; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.report_archive
    ADD CONSTRAINT fknn0f9lv0p0ayh39ur0hdj8pcm FOREIGN KEY (id_report) REFERENCES public.report(id_report);


--
-- Name: team fkok1m60njs4scy9iekna6cuwet; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.team
    ADD CONSTRAINT fkok1m60njs4scy9iekna6cuwet FOREIGN KEY (id_project) REFERENCES public.project(id_project);


--
-- Name: report fkpruq9ow6uaeh9ly8l573ve248; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.report
    ADD CONSTRAINT fkpruq9ow6uaeh9ly8l573ve248 FOREIGN KEY (id_project) REFERENCES public.project(id_project);


--
-- Name: sprint_report fkqho8jk6hyjtffbbd83kn5uthj; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.sprint_report
    ADD CONSTRAINT fkqho8jk6hyjtffbbd83kn5uthj FOREIGN KEY (id_report) REFERENCES public.report(id_report);


--
-- Name: student_historic fkqvhb2e0wg15i10vwrv9g3plbd; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_historic
    ADD CONSTRAINT fkqvhb2e0wg15i10vwrv9g3plbd FOREIGN KEY (id_class) REFERENCES public.class(id_class);


--
-- Name: report fkrppisgkj8yte7eropfc508eb4; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.report
    ADD CONSTRAINT fkrppisgkj8yte7eropfc508eb4 FOREIGN KEY (id_user_student) REFERENCES public."user"(id_user);


--
-- Name: student_historic fksoqkqpacxi7h4egbf4yxfainr; Type: FK CONSTRAINT; Schema: public; Owner: -
--

ALTER TABLE ONLY public.student_historic
    ADD CONSTRAINT fksoqkqpacxi7h4egbf4yxfainr FOREIGN KEY (id_user_student) REFERENCES public."user"(id_user);


--
-- PostgreSQL database dump complete
--





