name: Sync to GitLab

on:
  push:
    branches:
      - main
      - dev

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Push to GitLab
        run: |
          # Configura a URL com o token de autenticação
          # Troque a URL abaixo pela URL do seu projeto no GitLab (sem o https://)
          GITLAB_REPO="https://tools.ages.pucrs.br/fluxo-ages-2.0-alunos/backend-fluxo-alunos.git"
          
          git remote add gitlab "https://oauth2:${{ secrets.GITLAB_TOKEN }}@$GITLAB_REPO"
          
          # Envia a branch atual para o GitLab
          git push gitlab ${{ github.ref_name }} --force